<a href="https://colab.research.google.com/github/opassos/LetsCode/blob/main/Let's_Code_Projeto_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd

## 1) Carregar e unir as bases

In [ ]:
df_demog = pd.read_csv('/content/drive/MyDrive/1_demografico.csv', sep = ';')
df_renda = pd.read_csv('/content/drive/MyDrive/2_renda_gastos.csv', sep = ';')
df_bens = pd.read_csv('/content/drive/MyDrive/3_bens.csv', sep = ';')

In [ ]:
df = df_demog.merge(df_renda).merge(df_bens, left_index=True, right_index = True)
df.tail(1)

         ID Region  ... Number of Motorized Banca  Number of Motorcycle/Tricycle
41543  1788      Q  ...                         0                              1

[1 rows x 54 columns]

## EDA

In [ ]:
colunas = df.columns.to_list()
colunas

['ID',
 'Region',
 'Main Source of Income',
 'Agricultural Household indicator',
 'Household Head Sex',
 'Household Head Age',
 'Household Head Marital Status',
 'Household Head Class of Worker',
 'Type of Household',
 'Total Number of Family members',
 'Members with age less than 5 year old',
 'Members with age 5 - 17 years old',
 'Total number of family members employed',
 'Type of Building/House',
 'Type of Walls',
 'House Floor Area',
 'House Age',
 'Number of bedrooms',
 'Electricity',
 'Total Household Income',
 'Total Food Expenditure',
 'Bread and Cereals Expenditure',
 'Total Rice Expenditure',
 'Meat Expenditure',
 'Total Fish and  marine products Expenditure',
 'Fruit Expenditure',
 'Vegetables Expenditure',
 'Restaurant and hotels Expenditure',
 'Alcoholic Beverages Expenditure',
 'Tobacco Expenditure',
 'Clothing, Footwear and Other Wear Expenditure',
 'Housing and water Expenditure',
 'Imputed House Rental Value',
 'Medical Care Expenditure',
 'Transportation Expenditure',
 'Communication Expenditure',
 'Education Expenditure',
 'Miscellaneous Goods and Services Expenditure',
 'Special Occasions Expenditure',
 'Crop Farming and Gardening expenses',
 'Total Income from Entrepreneurial Acitivites',
 'Number of Television',
 'Number of CD/VCD/DVD',
 'Number of Component/Stereo set',
 'Number of Refrigerator/Freezer',
 'Number of Washing Machine',
 'Number of Airconditioner',
 'Number of Car, Jeep, Van',
 'Number of Landline/wireless telephones',
 'Number of Cellular phone',
 'Number of Personal Computer',
 'Number of Stove with Oven/Gas Range',
 'Number of Motorized Banca',
 'Number of Motorcycle/Tricycle']

In [ ]:
cols_cat = [
    'ID',
    'Region',
    'Main Source of Income',
    'Agricultural Household indicator',
    'Household Head Sex',
    'Household Head Marital Status',
    'Household Head Class of Worker',
    'Type of Household',
    'Type of Building/House',
    'Type of Walls',
    'Electricity',
 ]

In [ ]:
cols_num = [c for c in colunas if c not in cols_cat]
cols_num

['Household Head Age',
 'Total Number of Family members',
 'Members with age less than 5 year old',
 'Members with age 5 - 17 years old',
 'Total number of family members employed',
 'House Floor Area',
 'House Age',
 'Number of bedrooms',
 'Total Household Income',
 'Total Food Expenditure',
 'Bread and Cereals Expenditure',
 'Total Rice Expenditure',
 'Meat Expenditure',
 'Total Fish and  marine products Expenditure',
 'Fruit Expenditure',
 'Vegetables Expenditure',
 'Restaurant and hotels Expenditure',
 'Alcoholic Beverages Expenditure',
 'Tobacco Expenditure',
 'Clothing, Footwear and Other Wear Expenditure',
 'Housing and water Expenditure',
 'Imputed House Rental Value',
 'Medical Care Expenditure',
 'Transportation Expenditure',
 'Communication Expenditure',
 'Education Expenditure',
 'Miscellaneous Goods and Services Expenditure',
 'Special Occasions Expenditure',
 'Crop Farming and Gardening expenses',
 'Total Income from Entrepreneurial Acitivites',
 'Number of Television',
 'Number of CD/VCD/DVD',
 'Number of Component/Stereo set',
 'Number of Refrigerator/Freezer',
 'Number of Washing Machine',
 'Number of Airconditioner',
 'Number of Car, Jeep, Van',
 'Number of Landline/wireless telephones',
 'Number of Cellular phone',
 'Number of Personal Computer',
 'Number of Stove with Oven/Gas Range',
 'Number of Motorized Banca',
 'Number of Motorcycle/Tricycle']

In [ ]:
df[cols_cat].nunique()

ID                                  4162
Region                                17
Main Source of Income                  3
Agricultural Household indicator       3
Household Head Sex                     2
Household Head Marital Status          6
Household Head Class of Worker         7
Type of Household                      3
Type of Building/House                 6
Type of Walls                          6
Electricity                            2
dtype: int64

## 2) Relatorio

In [ ]:
def relatorio_quantitativo(df, cols, font_size = 7):

    style = [
        dict(selector="th", props=[("font-size", f'{font_size + 1}pt')]),
        dict(selector="td", props=[("font-size", f'{font_size    }pt')])
    ]
        
    relatorio = df[cols].describe()
    mediana = pd.Series(df[cols].apply(np.nanmedian, axis = 0), name = 'mediana')
    relatorio = relatorio.append(mediana).loc[['min', '25%', 'mediana', '75%', 'max', 'mean']]

    display(relatorio.T.style.format('{:.2f}').set_table_styles(style))

relatorio_quantitativo(df, cols_num)

## 3) Relatório sem outliers

In [ ]:
def is_outlier(col):
    Q1, Q3 = col.quantile((0.25, 0.75))
    IQR = Q3 - Q1
    return (col > Q3 + 1.5 * IQR) | (col < Q1 - 1.5 * IQR)

def input_outlier(col, value = None, verbose = False):
    if isinstance(value, str):
        if value == 'mediana':
            value = np.nanmedian(col)
        else:
            raise ValueError('value deve ser numérico, None ou "mediana".')
    outliers = is_outlier(col)
    print(f'Inputando {outliers.sum()} outliers com o valor {value} ...')
    col[outliers] = value
    return col

In [ ]:
df_num_outlier_none = df[cols_num].apply(input_outlier)

Inputando 68 outliers com o valor None ...
Inputando 667 outliers com o valor None ...
Inputando 589 outliers com o valor None ...
Inputando 434 outliers com o valor None ...
Inputando 161 outliers com o valor None ...
Inputando 2547 outliers com o valor None ...
Inputando 1583 outliers com o valor None ...
Inputando 2616 outliers com o valor None ...
Inputando 3151 outliers com o valor None ...
Inputando 1849 outliers com o valor None ...
Inputando 1024 outliers com o valor None ...
Inputando 999 outliers com o valor None ...
Inputando 2124 outliers com o valor None ...
Inputando 1878 outliers com o valor None ...
Inputando 2833 outliers com o valor None ...
Inputando 1716 outliers com o valor None ...
Inputando 3093 outliers com o valor None ...
Inputando 3705 outliers com o valor None ...
Inputando 3613 outliers com o valor None ...
Inputando 3764 outliers com o valor None ...
Inputando 2954 outliers com o valor None ...
Inputando 3379 outliers com o valor None ...
Inputando 5413 outliers com o valor None ...
Inputando 3422 outliers com o valor None ...
Inputando 5226 outliers com o valor None ...
Inputando 7217 outliers com o valor None ...
Inputando 3955 outliers com o valor None ...
Inputando 4201 outliers com o valor None ...
Inputando 8297 outliers com o valor None ...
Inputando 2660 outliers com o valor None ...
Inputando 783 outliers com o valor None ...
Inputando 188 outliers com o valor None ...
Inputando 6486 outliers com o valor None ...
Inputando 104 outliers com o valor None ...
Inputando 11 outliers com o valor None ...
Inputando 4087 outliers com o valor None ...
Inputando 2668 outliers com o valor None ...
Inputando 2242 outliers com o valor None ...
Inputando 510 outliers com o valor None ...
Inputando 8556 outliers com o valor None ...
Inputando 5443 outliers com o valor None ...
Inputando 489 outliers com o valor None ...
Inputando 10262 outliers com o valor None ...

In [ ]:
relatorio_quantitativo(df_num_outlier_none, cols_num)

## 4) Relatório com outliers tratados

In [ ]:
df_num_outlier_median = df[cols_num].apply(input_outlier, value = 'mediana')

Inputando 68 outliers com o valor 51.0 ...
Inputando 667 outliers com o valor 4.0 ...
Inputando 589 outliers com o valor 0.0 ...
Inputando 434 outliers com o valor 1.0 ...
Inputando 161 outliers com o valor 1.0 ...
Inputando 2547 outliers com o valor 40.0 ...
Inputando 1583 outliers com o valor 17.0 ...
Inputando 2616 outliers com o valor 2.0 ...
Inputando 3151 outliers com o valor 164079.5 ...
Inputando 1849 outliers com o valor 72985.5 ...
Inputando 1024 outliers com o valor 23324.0 ...
Inputando 999 outliers com o valor 16620.0 ...
Inputando 2124 outliers com o valor 7332.5 ...
Inputando 1878 outliers com o valor 8695.0 ...
Inputando 2833 outliers com o valor 1820.0 ...
Inputando 1716 outliers com o valor 4314.0 ...
Inputando 3093 outliers com o valor 7314.0 ...
Inputando 3705 outliers com o valor 270.0 ...
Inputando 3613 outliers com o valor 300.0 ...
Inputando 3764 outliers com o valor 2740.0 ...
Inputando 2954 outliers com o valor 22992.0 ...
Inputando 3379 outliers com o valor 10800.0 ...
Inputando 5413 outliers com o valor 1125.0 ...
Inputando 3422 outliers com o valor 6036.0 ...
Inputando 5226 outliers com o valor 1506.0 ...
Inputando 7217 outliers com o valor 880.0 ...
Inputando 3955 outliers com o valor 6804.0 ...
Inputando 4201 outliers com o valor 1500.0 ...
Inputando 8297 outliers com o valor 0.0 ...
Inputando 2660 outliers com o valor 19222.0 ...
Inputando 783 outliers com o valor 1.0 ...
Inputando 188 outliers com o valor 0.0 ...
Inputando 6486 outliers com o valor 0.0 ...
Inputando 104 outliers com o valor 0.0 ...
Inputando 11 outliers com o valor 0.0 ...
Inputando 4087 outliers com o valor 0.0 ...
Inputando 2668 outliers com o valor 0.0 ...
Inputando 2242 outliers com o valor 0.0 ...
Inputando 510 outliers com o valor 2.0 ...
Inputando 8556 outliers com o valor 0.0 ...
Inputando 5443 outliers com o valor 0.0 ...
Inputando 489 outliers com o valor 0.0 ...
Inputando 10262 outliers com o valor 0.0 ...

In [ ]:
relatorio_quantitativo(df_num_outlier_median, cols_num)

## 5) Relatório das variáveis qualitativas

In [ ]:
def relatorio_qualitativo(df, cols, font_size = 7):

    style = [
        dict(selector="th", props=[("font-size", f'{font_size + 1}pt')]),
        dict(selector="td", props=[("font-size", f'{font_size    }pt')])
    ]
    
    for col in cols:
        rel = pd.DataFrame({'freq_abs': df[col].value_counts().sort_index(),
                            'freq_acc': df[col].value_counts().sort_index().cumsum(),
                            'freq_rel': df[col].value_counts(normalize = True).sort_index().map('{:.2f}'.format),
                            'freq_rac': df[col].value_counts(normalize = True).sort_index().cumsum().map('{:.2f}'.format),
                            })
        rel = pd.concat({col: rel}, names=['Feature'])
        display(rel.T.style.set_table_styles(style))


relatorio_qualitativo(df, cols_cat[1:])

## 6) Separando os 10% com maior renda em um novo .csv

In [ ]:
col_renda = 'Total Household Income'
renda_alta = df[col_renda].quantile(0.9)
df_ricos = df[df[col_renda] > renda_alta].sort_values(col_renda, ascending = False)
# df_ricos.to_csv('NOME_DO_CSV.csv')
df_ricos.head()

         ID Region  ... Number of Motorized Banca  Number of Motorcycle/Tricycle
3860    354      C  ...                         0                              2
3513      7      C  ...                         0                              2
29329  1760      L  ...                         0                              1
21291   596      I  ...                         0                              3
35476  3222      N  ...                         0                              0

[5 rows x 54 columns]

## 7 e 8) Criando dummies e gerando relatório

In [ ]:
cols = cols_cat[2:5]
cols

['Main Source of Income',
 'Agricultural Household indicator',
 'Household Head Sex']

In [ ]:
df_dummy = pd.get_dummies(df, columns = cols)
df_dummy = df_dummy.drop(cols_cat, axis = 1, errors = 'ignore')
df_dummy['ricos10'] = df_dummy[col_renda] > renda_alta
df_dummy.groupby('ricos10').agg('mean').style.format('{:.2f}').highlight_max()

## Extra, por quartil

In [ ]:
df_dummy = pd.get_dummies(df, columns = cols)
df_dummy = df_dummy.drop(cols_cat, axis = 1, errors = 'ignore')
df_dummy['faixa_renda'] = pd.cut(df_dummy[col_renda], df_dummy[col_renda].quantile(np.linspace(0, 1, 11)))
df_dummy.groupby('faixa_renda').agg('mean').T.style.format('{:.2f}').bar(axis = 1)